(window.webpackJsonp=window.webpackJsonp||[]).push([[56],{383:function(t,e,a){"use strict";a.r(e);var s=a(4),r=Object(s.a)({},(function(){var t=this,e=t._self._c;return e("ContentSlotsDistributor",{attrs:{"slot-key":t.$parent.slotKey}},[e("h1",{attrs:{id:"git使用经验1"}},[e("a",{staticClass:"header-anchor",attrs:{href:"#git使用经验1"}},[t._v("#")]),t._v(" git使用经验1")]),t._v(" "),e("h2",{attrs:{id:"报错信息"}},[e("a",{staticClass:"header-anchor",attrs:{href:"#报错信息"}},[t._v("#")]),t._v(" 报错信息")]),t._v(" "),e("div",{staticClass:"language- line-numbers-mode"},[e("pre",{pre:!0,attrs:{class:"language-text"}},[e("code",[t._v("Updates were rejected because the remote contains work that you do  not have locally. This is usually caused by another repository pushing to the same ref. You may want to first integrate the remote changes  (e.g., 'git pull ...') before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.\n")])]),t._v(" "),e("div",{staticClass:"line-numbers-wrapper"},[e("span",{staticClass:"line-number"},[t._v("1")]),e("br"),e("span",{staticClass:"line-number"},[t._v("2")]),e("br")])]),e("h2",{attrs:{id:"解决"}},[e("a",{staticClass:"header-anchor",attrs:{href:"#解决"}},[t._v("#")]),t._v(" 解决")]),t._v(" "),e("p",[t._v("上述问题在开发过程中老是出现，时灵时不灵的，还是要搞清楚了，一次搞懂，终生收益。")]),t._v(" "),e("p",[t._v("错误原因：在github上修改了文件，没有更新到本地就上传，永远记住，处理冲突只能在本地处理，所以push之前一定要先pull在本地处理完冲突，再push。")]),t._v(" "),e("p",[t._v("解决方法：本地和远程的文件应该合并后才能上传本地的新文件\n具体方法：")]),t._v(" "),e("p",[t._v("1、先pull拉下来，会自动合并的，")]),t._v(" "),e("p",[t._v("2、再上传")])])}),[],!1,null,null,null);e.default=r.exports}}]);